[project]
name = "cadastro-itens"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "LuizWKM", email = "luizricardowm@outlook.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
cadastro-itens = "cadastro_itens:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
